import { RoleKey } from '../types';

export const ASSIGNABLE_ROLES_BY_LEVEL: Record<RoleKey, RoleKey[]> = {
  EMPLOYEE: [],
  DEPARTMENT_HEAD: ['EMPLOYEE'],
  DEPUTY_CHAIR: ['DEPARTMENT_HEAD', 'EMPLOYEE'],
  CHAIRMAN: ['DEPUTY_CHAIR', 'DEPARTMENT_HEAD', 'EMPLOYEE'],
  AGGREGATOR: ['DEPUTY_CHAIR', 'DEPARTMENT_HEAD', 'EMPLOYEE'],
};
