import { addDays, subDays } from 'date-fns';
import { Task } from '../types';

const today = new Date();

const iso = (date: Date) => date.toISOString();

export const SAMPLE_TASKS: Task[] = [
  {
    id: 'T-001',
    title: 'Hoàn thiện báo cáo cải cách hành chính',
    description: 'Tổng hợp số liệu và phản hồi theo biểu mẫu của Sở Nội vụ.',
    ownerRole: 'AGGREGATOR',
    assigneeRole: 'DEPARTMENT_HEAD',
    assigneeName: 'Trần Thị Mai',
    department: 'Tư pháp',
    source: 'SO',
    dueDate: iso(addDays(today, 3)),
    status: 'IN_PROGRESS',
    progress: 64,
    attachments: 3,
  },
  {
    id: 'T-002',
    title: 'Rà soát hồ sơ đất đai tồn đọng',
    description: 'Xử lý hồ sơ quá hạn và gửi báo cáo kết quả cho UBND tỉnh.',
    ownerRole: 'CHAIRMAN',
    assigneeRole: 'DEPUTY_CHAIR',
    assigneeName: 'Lê Quốc Bảo',
    department: 'Tài nguyên',
    source: 'UBND_TINH',
    dueDate: iso(subDays(today, 2)),
    status: 'REVIEW',
    progress: 82,
  },
  {
    id: 'T-003',
    title: 'Tổ chức tuyên truyền pháp luật quý I',
    description: 'Chuẩn bị nội dung và lịch triển khai đến từng phòng ban.',
    ownerRole: 'DEPARTMENT_HEAD',
    assigneeRole: 'EMPLOYEE',
    assigneeName: 'Nguyễn Văn Minh',
    department: 'Tư pháp',
    source: 'NOI_BO',
    dueDate: iso(addDays(today, 9)),
    status: 'IN_PROGRESS',
    progress: 45,
  },
  {
    id: 'T-004',
    title: 'Thẩm định hồ sơ đầu tư dự án X',
    description: 'Phối hợp phòng Kinh tế và UBND huyện hoàn tất thẩm định.',
    ownerRole: 'DEPUTY_CHAIR',
    assigneeRole: 'DEPARTMENT_HEAD',
    assigneeName: 'Trần Thị Mai',
    department: 'Kinh tế',
    source: 'UBND_TINH',
    dueDate: iso(addDays(today, 1)),
    status: 'NEW',
    progress: 10,
  },
  {
    id: 'T-005',
    title: 'Cập nhật cơ sở dữ liệu nhân sự',
    description: 'Admin hỗ trợ điều chỉnh phân quyền phòng ban.',
    ownerRole: 'ADMIN',
    assigneeRole: 'ADMIN',
    assigneeName: 'Admin Hệ thống',
    department: 'CNTT',
    source: 'CHU_TICH',
    dueDate: iso(addDays(today, 14)),
    status: 'IN_PROGRESS',
    progress: 30,
  },
  {
    id: 'T-006',
    title: 'Tổng hợp KPI quý gần nhất',
    description: 'Phòng Tổng hợp gửi báo cáo KPI lên Chủ tịch.',
    ownerRole: 'CHAIRMAN',
    assigneeRole: 'AGGREGATOR',
    assigneeName: 'Đỗ Gia Hưng',
    department: 'Tổng hợp',
    source: 'CHU_TICH',
    dueDate: iso(subDays(today, 1)),
    status: 'IN_PROGRESS',
    progress: 58,
  },
  {
    id: 'T-007',
    title: 'Kiểm tra công tác chuẩn bị mùa mưa bão',
    description: 'Trưởng phòng giao nhân viên hoàn tất checklist.',
    ownerRole: 'DEPARTMENT_HEAD',
    assigneeRole: 'EMPLOYEE',
    assigneeName: 'Nguyễn Văn Minh',
    department: 'Kinh tế',
    source: 'UBND_HUYEN',
    dueDate: iso(subDays(today, 5)),
    status: 'NEW',
    progress: 0,
  },
  {
    id: 'T-008',
    title: 'Đánh giá mức hoàn thành nhân viên phòng Tư pháp',
    description: 'Trưởng phòng tổng hợp kết quả theo từng nhiệm vụ.',
    ownerRole: 'DEPARTMENT_HEAD',
    assigneeRole: 'DEPARTMENT_HEAD',
    assigneeName: 'Trần Thị Mai',
    department: 'Tư pháp',
    source: 'NOI_BO',
    dueDate: iso(addDays(today, 6)),
    status: 'REVIEW',
    progress: 72,
  },
];
